overrides:
  '@hono/node-server@<1.19.10': '>=1.19.10'
  express-rate-limit@>=8.2.0 <8.2.2: '>=8.2.2'
  hono@<4.12.4: '>=4.12.4'

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@openfort/openfort-node'

trustPolicy: no-downgrade

blockExoticSubdeps: true